# Form implementation generated from reading ui file 'ui_source_add.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(646, 403)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 290, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(130, 80, 451, 191))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.ipLabel_2 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.ipLabel_2.setObjectName("ipLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.ipLabel_2)
        self.ipLineEdit_2 = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.ipLineEdit_2.setObjectName("ipLineEdit_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ipLineEdit_2)
        self.portLabel = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.portLabel.setObjectName("portLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.portLabel)
        self.portLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.portLineEdit.setObjectName("portLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.portLineEdit)
        self.Label = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.Label.setObjectName("Label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Label)
        self.LineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.LineEdit.setObjectName("LineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEdit)
        self.Label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Label_2)
        self.LineEdit_2 = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEdit_2)
        self.Label_4 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Label_4)
        self.LineEdit_4 = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEdit_4)
        self.Label_5 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.Label_5.setObjectName("Label_5")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Label_5)
        self.LineEdit_5 = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEdit_5)
        self.Label_6 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.Label_6.setObjectName("Label_6")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Label_6)
        self.LineEdit_6 = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.LineEdit_6.setObjectName("LineEdit_6")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEdit_6)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        # self.ipLabel_2.setText(_translate("Dialog", "数据库ip"))
        # self.portLabel.setText(_translate("Dialog", "数据库port"))
        # self.Label.setText(_translate("Dialog", "数据库实例"))
        # self.Label_2.setText(_translate("Dialog", "数据库名"))
        # self.Label_4.setText(_translate("Dialog", "用户名"))
        # self.Label_5.setText(_translate("Dialog", "密码"))
        # self.Label_6.setText(_translate("Dialog", "类型"))
        self.ipLabel_2.setText(_translate("Dialog", "ip"))
        self.portLabel.setText(_translate("Dialog", "port"))
        self.Label.setText(_translate("Dialog", "instance"))
        self.Label_2.setText(_translate("Dialog", "libraryName"))
        self.Label_4.setText(_translate("Dialog", "username"))
        self.Label_5.setText(_translate("Dialog", "password"))
        self.Label_6.setText(_translate("Dialog", "type"))
